spring:
  application:
    name: speech-api
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: app_user
    password: Beyond80.Bucks
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true

server:
  port: 8080

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE