spring:
  application:
    name: speech-api
  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: app_user
    password: Beyond80.Bucks
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

server:
  port: 8080
  shutdown: graceful